version: '3.3'
services:
    rtsp_server_live555:
        image: rtsp_server_live555:latest
    video_frame_extraction_app:
        build:
            context: ./video_frame_extraction_app
        image: video_frame_extraction_app:latest
        environment:
            - REDIS_HOST=redis
        ports:
            - "5000:5000"
        depends_on: 
            - redis
            - rtsp_server_live555
        devices:
            - ${WEBCAM_DEVICE}:${WEBCAM_DEVICE}
        privileged: true
        restart: always
    object_dectection_app:
        build:
            context: ./object_detection_app
        image: object_detection_app:latest
        environment:
            - REDIS_HOST=redis
            # - DISPLAY=${X11_HOST_IP}:0
        volumes:
            - ./data:/data
            # - /tmp/.X11-unix:/tmp/.X11-unix
        ports:
            - "7000:7000"
        depends_on:
            - redis
            - video_frame_extraction_app  
        restart: always  
    feature_indexer_app:
        build:
            context: ./feature_indexer_app
        image: feature_indexer_app:latest
        environment:
            - REDIS_HOST=redis
            - ES_HOST=elasticsearch
        volumes:
            - ./data:/data
        depends_on:
            - redis
            - elasticsearch   
        restart: always
    redis:
        image: redis
        # volumes:
        #     - redis_data:/data   
        restart: always     
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        ports:
            - 9200:9200
        # volumes:
        #     - es_data:/data 
        restart: always
    kibana:
        image: docker.elastic.co/kibana/kibana:6.3.2
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        restart: always
# volumes:
#     redis_data:
#     es_data: